### ISSUE TITLE
Decide on scope for branch protection

### ISSUE THREAD

**Issue by jamesmisson** [UniversalViewer/universalviewer#1206]

**Comment by LlGC-jop** [comment]
Just found I can't view the relevant section of the repo :( but I'd suggest we use the classic branch protection, rather than the rulesets, and have the following:

- Apply to dev and main, using the `[dm][ea][vi]*` pattern - Github uses fnmatch, hence the weird syntax
- Require a PR before merging
- Require 2 reviews
- Dismiss stale approvals when new commits pushed

I think that should cover everything.

**Comment by jamesmisson** [comment]
I can't see the settings either, but that all sounds reasonable to me (as someone with no experience of this beyond the docs). I don't suppose there's much chance anyone will create a new branch beginning with the letters mai- but might be something to bear in mind.

**Comment by LlGC-jop** [comment]
Maybe we should also come up with a naming convention for branches as well? Not that we could enforce that in forks etc. but at least in this repo?

There's ones like `feature/v4-fix-images` which doesn't tell you anything. An issue number in the branch name would tell you why it exists etc.

Branch cleanup might be a good future admin task. That images one is 2 years old and hasn't been merged!

**Comment by LlGC-jop** [comment]
@demiankatz

- Sure. We normally keep the last 3 or 4 release branches in the NLW repos. Perhaps we protect those so that can't ever be pushed to and deletion requires an admin?
- Good point, we can talk about that after the sprint call when we look at implementing, and see what our options are?
- I just assumed that 2 was the norm on the UV after the recent sprint :) but 1 is fine with me

**Comment by demiankatz** [comment]
Yes, I think protecting release branches makes sense; we might as well set that up while we're at it, even if we don't use it right away.

Happy to discuss the other preferences on our call!

And I think two approvals is ideal, but I was being extra strict since we had so many people and I felt we had the luxury. Under more normal circumstances, I'll settle for one most of the time. :-)

**Comment by demiankatz** [comment]
We agreed to start with 1 approval for now. We also found that the new branch protection system allows us to specify branches without needing to use a complex pattern. Branch protection has been applied to the main UV repository.
