### ISSUE TITLE
Turn on GitHub branch protection

### ISSUE THREAD

**Issue by jamesmisson** [UniversalViewer/universalviewer#1207]

**Comment by LlGC-jop** [comment]
Just found I can't view the relevant section of the repo :( but I'd suggest we use the classic branch protection, rather than the rulesets, and have the following:

- Apply to dev and main, using the `[dm][ea][vi]*` pattern - Github uses fnmatch, hence the weird syntax
- Require a PR before merging
- Require 2 reviews
- Dismiss stale approvals when new commits pushed

I think that should cover everything.

**Comment by jamesmisson** [comment]
Hi @demiankatz and @LlGC-jop , shall we schedule a quick meeting to discuss and implement this (along with https://github.com/UniversalViewer/universalviewer/issues/1206)? Besides the stand ups, I'm available all afternoon/early evening today and tomorrow.

**Comment by LlGC-jop** [comment]
Ditto.
