### ISSUE TITLE
Fields not translated

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#148]
Hello, Attribution and License need to be translated to Welsh, but should this be done through the Manifest or by the Viewer?

![translation](https://cloud.githubusercontent.com/assets/1083554/9936646/dfce7cf0-5d54-11e5-80f1-91c299c28c65.png)

Thanks,
Dylan

**Comment by LlGC-szw** [comment]
Just to clarify the systems team have given us a manifest with the following data:

description: "Transcripts of poems by Guillaume de Machaut.",
license: "http://hdl.handle.net/10107/PublicDomainMark",
logo: {
@id: "http://dams.llgc.org.uk/iiif/2.0/image/logo/full/400,/0/default.jpg",
service: {
@context: " http://iiif.io/api/image/2/context.json",
@id: " http://dams.llgc.org.uk/iiif/2.0/image/logo",
profile: " http://iiif.io/api/image/2/level1.json"
}
},
attribution: "Llyfrgell Genedlaethol Cymru – The National Library of Wales",
related: {
@id: "http://cat.llgc.org.uk/cgi-bin/gw/chameleon?lng=en&search=KEYWORD&function=CARDSCR&u1=12101&t1=004369987",
format: "text/html"
},

but as you can see there are no language attributes for fields outside of the metadata section. They are asking for any advice on this matter.

**Comment by tomcrane** [comment]
Hi Sarah and Dylan

The viewer should provide translations for attribution and license, as these must be shown to the user. They are part of the required UI that happen to use the same label as the name of the property they display. For the arbitrary metadata list the manifest must supply names and values, but cannot do so for these "top level" properties.

So if they are not there we need to add them to the Transifex strings.

It's not completely clear cut which of the metadata names should be translated, because most of them are only used internally to the viewer (e.g., we don't need to translate viewingHint because we never show that as a human-readable label). 

http://prezi-21.iiif.io/api/presentation/2.1/#b-summary-of-metadata-requirements

Just because the IIIF property is "description" it doesn't mean a viewer has to present the content with that label - e.g., you could imagine a simple viewer that presents "name" as a header and "description" as a subhead, without any labels. But is makes sense that the UV should know about "attribution" and "license" at least.

Tom

**Comment by edsilv** [comment]
That was a pretty quick fix, have pushed an update:

http://localhost:8001/examples/?manifest=http%3A%2F%2Fdams.llgc.org.uk%2Fiiif%2F2.0%2F4389767%2Fmanifest.json&locale=cy-GB%3ACymraeg%2Cen-GB%3AEnglish%20(GB)&jsonp=null&testids=false&defaultToFullScreen=false#?c=0&m=0&s=0&cv=0&z=0%2C-0.4027%2C1%2C1.8053

**Comment by edsilv** [comment]
Have added the new strings to transifex.

**Comment by LlGC-szw** [comment]
Hi Ed, thanks for such a quick response. Will do the translations this afternoon before 4 and let you know when they're signed off.

**Comment by edsilv** [comment]
I haven't done a new release yet as there's currently a bug in IE8. You may want to hold off deploying the latest UV until this is fixed.

**Comment by LlGC-szw** [comment]
Yes we will wait until it's ready. Thanks again.

**Comment by LlGC-szw** [comment]
Translation all done.
