### ISSUE TITLE
Enable use without iFrame/Support for Rails Asset Pipeline

### ISSUE THREAD

**Issue by tpendragon** [UniversalViewer/universalviewer#221]
We're currently using this in a Rails project (http://github.com/pulibrary/plum), but this project is entirely incompatible with the asset pipeline for a few reasons:

A) embed.js relies on knowing where JS dependencies are relative to itself, and what they're named. The asset pipeline adds a checksum to the end of assets for caching reasons, so the names aren't reliable.

B) The script relies on knowing where the image dependencies are. This is a similar problem to above. We can solve it in OpenSeadragon because there are a bunch of config options for setting those locations, which we can handle dynamically (although it's a bit complicated.)

C) Requires an iFrame. In the Rails context this means for us to get the app running we'd have to spin up this gem as an engine that provides a page where the viewer actually sits, rather than just embedding the viewer inline.

Because of these reasons the only way we've been able to get it to work is to avoid Rails entirely and effectively have nginx serve up all the assets (via putting them in Rails' public directory). It works, but it makes packaging it up and using the work between projects difficult, and means holding a full mirror of UV within the project's source control.

Any plans to add configurability of asset locations, and a way to add the viewer without using an iFrame?

**Comment by edsilv** [comment]
Yep: https://github.com/UniversalViewer/universalviewer/issues/156

This will have a useIframe:boolean option (scheduled for milestone UV 2.0 which I will start soon). The UV already works without an iframe if you load app.html directly:

http://universalviewer.io/examples/uv/app.html?manifestUri=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb18035723%2Fmanifest

It sounds like you need uv.js though in order to instantiate it inline.

Is it these 3 lines specifically in embed.js that are causing you problems?

https://github.com/UniversalViewer/universalviewer/blob/master/src/lib/embed.js#L185

These are all related to it being in an iframe so hopefully can be jettisoned when using uv.js.

Do you mean the Openseadragon zoom/rotate buttons aren't being found? We could potentially make their base path a UV config option for you to override with the data-config attribute on the embedding div.

https://github.com/UniversalViewer/universalviewer/wiki/Embedding#data-config

**Comment by tpendragon** [comment]
> The UV already works without an iframe if you load app.html directly

Right, but we can't really do an app.html in Rails-land within the asset pipeline, unless we build a whole Rails engine (effectively a mini-application that just has the necessary HTML)

**Comment by tpendragon** [comment]
> Is it these 3 lines specifically in embed.js that are causing you problems?

Yes

> Do you mean the Openseadragon zoom/rotate buttons aren't being found? We could potentially make their base path a UV config option for you to override with the data-config attribute on the embedding div.

That and any other images the library expects to find in specific locations.

**Comment by edsilv** [comment]
> That and any other images the library expects to find in specific locations.

I'm not familiar with the rails pipeline unfortunately. Presumably this also includes any image paths included in the UV's theme css files? This sounds like a problem that must be fairly common when dealing with 3rd party libraries? Are there any precedents out there we could learn from?

**Comment by edsilv** [comment]
I've just spoken to some rails guys and they suggested serving the static uv files from the /public directory, bypassing the rails pipeline?

**Comment by edsilv** [comment]
Or this could work: https://github.com/spohlenz/digestion

**Comment by tpendragon** [comment]
> I've just spoken to some rails guys and they suggested serving the static uv files from the /public directory, bypassing the rails pipeline?

Yes, that's what we're doing. It works, but it makes sharing that between apps tough and you lose the benefits of the pipeline. Looking into popping that public folder in an engine instead, at least, but I've never tried it before.

**Comment by edsilv** [comment]
Just having another look at this:

https://github.com/spohlenz/digestion

Are you using rails >3.1.1?

> This project is no longer necessary as of Rails 3.1.1 and should be considered deprecated. The Rails asset pipeline now compiles asset files both with and without digests.

> The asset pipeline is a great new component of Rails 3.1. However it has a feature known as fingerprinting that makes it impossible to properly incorporate many popular JavaScript libraries (including TinyMCE, CKEditor and FancyZoom to name just a few) into the asset pipeline.
