### ISSUE TITLE
Timeout of 'Requires Registration' content

### ISSUE THREAD

**Issue by jennpb** [UniversalViewer/universalviewer#223]
In user testing on the existing WL site (using the player), our UX specialist reports:

"I did some testing with someone who mentioned that when he’s reading docs that are less than 100 years old, he times out whilst he’s reading. He then has to accept the terms again but that takes him back to the beginning of the doc. We discussed this at the beginning of our test session last week and I’ve cut the relevant section of the video.
https://drive.google.com/file/d/0B7c9GFIDZ8nQbURReFQxSFhQdkE/view?usp=sharing"

So two issues:
- Timeout may be happening too early (is this a policy decision?)
- Timeout returns user to first image, requiring them to remember where they left off. (my inclination would be to return user to where they left off).

**Comment by tomcrane** [comment]
The UV has the session time-to-live imposed by the server (Wellcome set to 10 minutes because of worries about people leaving archives open on public computers). This 10 minute time-to-live gets reset for each interaction with a new image, if the client verifies a stored token for each change of image. After https://github.com/UniversalViewer/universalviewer/issues/183 is done, the UV will keep the session running between different item pages.

The effect of a timeout (after 10 mins of inactivity) would be to trigger a login prompt *at the next interaction that changes the image*. This will not reload the viewer, so the user will stay exactly where they are.

One potential issue that may need addressing if it comes up: 

* I open an image that is protected - and I don't zoom in
* I walk away and make tea for 11 minutes
* I come back in zoom in to the same image - no navigation has occurred

In this scenario, no state change has happened in the viewer, no script has been triggered outside the context of the seadragon canvas. When I zoom in, it will go very blurry because seadragon can't load in higher res tiles to replace the scaled up low res ones. The UV can't see this happening.

The current Wellcome Player gets round this by monitoring the timeout of logins and triggering the behaviour that caused the UX problem above. The UV could possibly re-trigger a login prompt if it keeps track of tokens, but the problem is that it's not listening for an event that would trigger a re-check of the token - unless we have some setTimeout loop that checks whether tokens in the current store are still good for the image being displayed.

**Comment by tomcrane** [comment]
(this could be fairly infrequent - every 5 seconds or something - and doesn't involve re-obtaining the token, just noting the TTL it had **when** acquired against the time elapsed **since** it was acquired).

**Comment by jennpb** [comment]
We're going to keep the 10 minute timeout for now but good to know the UX issue will be resolved by #183
