### ISSUE TITLE
Download Option

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#23]
Hi, could the download option be added back as an option in the config?

Thanks,
Dylan

**Comment by edsilv** [comment]
Hi,

I've been working on a download option for the BL today. If you check out the universal viewer "bl" branch, there's a new `bl-seadragon-extension`:

    https://github.com/UniversalViewer/universalviewer/tree/bl/src/extensions/bl-seadragon-extension

and `bl-footerpanel-module`:

    https://github.com/UniversalViewer/universalviewer/tree/bl/src/modules/bl-footerpanel-module

which contains the download button. I created a BL-specific extension for this as download is not considered a "core" capability of the viewer, rather something that can be implemented differently for each institution.

The BL are making use of the new `externalContentDialogue`:

    https://github.com/UniversalViewer/universalviewer/blob/bl/src/modules/uv-dialogues-module/externalContentDialogue.ts

This can be configured to display a uri in an iframe overlaying the viewer. The idea is that the BL can create a page on their site that an image id can be passed to in order to display a list of download options.

Perhaps this could be a good option for the NLW too? Alternatively a custom download dialogue could be made similar to that on the Wellcome Player.

In any event, we should create a new NLW extension which can contain all non-core functionality.

**Comment by edsilv** [comment]
A "core" implementation of download has been added: https://github.com/UniversalViewer/universalviewer/commit/a5f471cadc1f0dc3a54a03b121225bcd194c6b10

This uses the IIIF image api to download arbitrary crops of the OpenSeadragon-zoomed image, as well as the image at the original size, and at a configurable maximum width.

For the download option to be visible in the bottom left corner of the UV, you need to be in "single-up" mode - this is due to the IIIF image protocol only supporting arbitrary tiles of single images.
