### ISSUE TITLE
attribution overlay

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#237]
![screenshot from 2016-02-01 17 02 06](https://cloud.githubusercontent.com/assets/1083554/12724466/fc1e012e-c905-11e5-860c-e8754c3e4db3.png)

Hi, is there a way of stopping the attribution overlay from displaying?
Thanks,
Dylan

**Comment by tomcrane** [comment]
Hi Dylan - it depends on whether you want the attribution shown when someone opens the manifest elsewhere - in some other viewer, on some other domain. If the answer is no, then do as Wellcome did and simply not include an explicit attribution property in the manifest. You could put the same text in a metadata field with the label "Attribution" instead, and it would appear in the more info panel.

Before going for this option, we considered adding a config to the viewer so that it would not display the attribution notice for manifests coming from a configured "home" domain - allowing you to embed it without attribution on your site, but with attribution on anyone else's.

In the 2.1 draft the wording has changed slightly: http://iiif.io/api/presentation/2.1/#rights-and-licensing-properties. If you take the view that your own web site can convey the attribution information to the user without having it pop up in the UV, then this approach is valid. It has not been implemented yet though.

**Comment by LlGC-dwj** [comment]
Thank you Tom, it's something we will keep in mind for future developments.
