### ISSUE TITLE
@id for image service in manifest ignored

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#251]
The "@id" attribute for an image service in the manifest is used to fetch the info.json,
but from that point on, it uses the "@id" that is stored in that info.json.

manifest:
```
[..]
resource: {
  service: {
    @id: "http://localhost/IIIF/image/archive.ugent.be%3A422E3B3C-188F-11E2-BBAF-A1630D0ED9C1%3ADS.101",
    @context: "http://iiif.io/api/image/2/context.json",
    profile: "http://iiif.io/api/image/2/level1.json"
  },
  @id: "http://localhost/IIIF/image/archive.ugent.be%3A422E3B3C-188F-11E2-BBAF-
A1630D0ED9C1%3ADS.101/full/full/0/native.jpg",
  @type: "dctypes:Image",
  height: 3867,
  format: "image/jpeg",
  width: 2461
}
[..]
```

info.json
```
{
  "@context" : "http://iiif.io/api/image/2/context.json",
  "@id" : "http://localhost/IIIF/image/archive/ugent/be/422E3B3C/188F/11E2/BBAF/A1630D0ED9C1/DS.101",
  "protocol" : "http://iiif.io/api/image",
  "width" : 2461,
  "height" : 3867,
  "tiles" : [
     { "width" : 256, "height" : 256, "scaleFactors" : [ 1, 2, 4, 8, 16 ] }
  ],
  "profile" : [
     "http://iiif.io/api/image/2/level1.json",
     { "formats" : [ "jpg" ],
       "qualities" : [ "native","color","gray" ],
       "supports" : ["regionByPct","sizeByForcedWh","sizeByWh","sizeAboveFull","rotationBy90s","mirroring","gray"] }
  ]
}
```

In the above example, the path is rewritten so that the IIPServer has a path relative to its
base directory (FILESYSTEM_PREFIX):
```
archive/ugent/be/422E3B3C/188F/11E2/BBAF/A1630D0ED9C1/DS.101
```

I know boths ids should be equal, but I have to do all kinds of url rewriting to get from
an identifier to a real file path that the IIPServer understands.

Or is it this more a job for the IIPServer, to do some basic resolving (i.e. rewriting, not database lookups)?

**Comment by tomcrane** [comment]
Hi @nicolasfranck,

To check I understand:

You generate http://localhost/IIIF/image/archive.ugent.be%3A422E3B3C-188F-11E2-BBAF-A1630D0ED9C1%3ADS.101 in the manifest so that you can rewrite to the real IIPImage instance. This @id URL in the manifest **will** give an info.json as the response.

However, because IIPImage generates the info.json, it generates the @id without knowledge of your rewrite rule. It generates the info.json @id as what it thinks it should be. 

The @id returned by the info.json MUST be the one used by the UV for tile requests, because it is the authoritative source and may have been redirected for other purposes. The UV should not use the @id in the manifest once it has the info.json. In your case, the UV (via Open Seadragon) can't use this info.json @id for tile requests, because image requests made using it won't resolve.

You could solve this in two ways - 

1) do more rewriting on the way in, so that 

```
http://localhost/IIIF/image/archive/ugent/be/422E3B3C/188F/11E2/BBAF/A1630D0ED9C1/DS.101/info.json
http://localhost/IIIF/image/archive/ugent/be/422E3B3C/188F/11E2/BBAF/A1630D0ED9C1/DS.101/full/full/0/default.jpg```

..both resolve, or

2) do some rewriting of the info.json response, to modify the @id returned in the info.json to something that will work.

I have a similar situation, and actually use both techniques - rewriting request paths and response bodies. But I have other reasons to modify the outgoing info.json, such as adding auth services to it.

Tom

**Comment by tomcrane** [comment]
(you would need to escape the slashes in my example as they form part of the image identifier)

**Comment by nicolasfranck** [comment]
That's indeed what I meant. I'll just catch the request to the info.json in another application (that communicates with the IIPServer) where I can change the response from the IIPServer. 

Thanks!
