### ISSUE TITLE
What's it take to trigger UV token-based auth?

### ISSUE THREAD

**Issue by tpendragon** [UniversalViewer/universalviewer#261]
I have a service in the root of my manifest that looks like...

```json
{
  "@context": "http://iiif.io/api/presentation/2/context.json",
  "@id": "http://localhost:3000/concern/scanned_resources/d791sg16q/manifest",
  "@type": "sc:Manifest",
  "label": "Unknown",
  "service": [
    {
      "@context": "http://iiif.io/api/auth/0/context.json",
      "@id": "http://localhost:3000/users/auth/cas",
      "label": "Login to Plum using CAS",
      "description": "Work please?",
      "profile": "http://iiif.io/api/auth/0/login",
      "service": [
        {
          "@id": "http://localhost:3000/iiif/token",
          "@context": "http://iiif.io/api/auth/0/context.json",
          "profile": "http://iiif.io/api/auth/0/token"
        }
      ]
    }
  ]
}
````

And it never seems to actually try to hit the token. I thought maybe UV required canvases to work, but I put in filler canvases with no images, but while UV loads it never tries to log in, there's no login button or anything. What am I missing?

**Comment by tomcrane** [comment]
Hi Trey,

Do you want to use auth to protect the manifest, or the image services referenced by the manifest?

Although the auth spec could be used to enforce access control on any IIIF resource, at the moment the UV implementation does not attempt to enforce auth on the initial manifest load. 

Is your initial manifest publicly available? If I requested it would I get HTTP 401 (but with the same full manifest as the response body)? It would be possible to support the auth flow on the full manifest like this, but what resources would you be protecting by doing this? Each image service would still need its own auth service otherwise I could just interact with the image service directly, bypassing whatever the manifest says. Or make another manifest that doesn't mention auth.

If all the image services in your manifest use the same auth services, then the user experience in the UV is going to be similar to a "manifest-level" auth because the UV remembers the tokens it has used from image to image. So even though what is actually happening is at the individual image service level (as it must be) the effect is of being challenged on initial load of the full item and then no further challenges while reading through the pages of the work (unless your session times out or you delete cookies or log out...).

Example:

http://wellcomelibrary.org/item/b18184273

This uses a simplified "clickthrough" login but the actual auth spec implementation is the same - the opened tab sets a cookie, the UV acquires a token that represents the cookie - but once you've done this for the first image you've done it for all. The auth services aren't protecting the manifest, which has no secrets.

Tom

**Comment by tpendragon** [comment]
> Do you want to use auth to protect the manifest, or the image services referenced by the manifest?

Auth as a service to show that there are canvases in this sequence which you need to authenticate to see.

> Is your initial manifest publicly available?

It could be? Could either do 401 with a response body, or just give back a manifest with the login service.

> Each image service would still need its own auth service otherwise I could just interact with the image service directly, bypassing whatever the manifest says.

Auth still needs to be enforced at the image level, for sure. I suppose there are two possible workflows, and I'm not sure which we want:

1) Display empty images for every canvas you're not allowed to see, and force auth when accessing that image. This seems to be what Wellcome is doing, and we can support by moving the auth service into the image services.

2) Only display those canvases which you have permission to see (what I'd assumed we'd do.)

@jpstroop Are we okay with option 1? If we prefer option 2, then we need challenge-on-load.

**Comment by tpendragon** [comment]
@tomcrane A use case for challenge on load would be collections - there will certainly be private items which require on-campus access that we don't want to display an empty canvas for.

**Comment by irv** [comment]
the request for info.json needs to return 401 with a body that contains the auth service for UV to do anything

**Comment by tpendragon** [comment]
Oh! So UV doesn't use the presentation API's auth at all?

**Comment by tomcrane** [comment]
Hi @tpendragon 

The UV uses (or will use) the auth service assertions in the manifest as hints - information up front to help optimise things like drawing a whole field of thumbnails, or providing UI hints that certain images are subject to auth without having to dereference every info.json in a 1000-page manifest.

There's a discussion here although some of it is a little out of date:
https://github.com/IIIF/iiif.io/issues/526

To summarise:

When you assert the image services in the manifest, you could also assert the auth services on them:

```

{
    "@id": "http://wellcomelibrary.org/iiif/b17564980/imageanno/391fb5ab-6092-429f-9b91-e4c74de4c24a",
    "@type": "oa:Annotation",
    "motivation": "sc:painting",
    "resource": {
        "@id": "http://wellcomelibrary.org/iiif-img/b17564980-0/391fb5ab-6092-429f-9b91-e4c74de4c24a/full/!1024,1024/0/default.jpg",
        "@type": "dctypes:Image",
        "format": "image/jpeg",
        "height": 1024,
        "width": 683,
        "service": [
            {
                "@context": "http://iiif.io/api/image/2/context.json",
                "@id": "http://wellcomelibrary.org/iiif-img/b17564980-0/391fb5ab-6092-429f-9b91-e4c74de4c24a",
                "profile": "http://iiif.io/api/image/2/level1.json",
                "service": [
                    {
                        "@context": "http://iiif.io/api/auth/0/context.json",
                        "@id": "http://wellcomelibrary.org/iiif/accepttermslogin",
                        "profile": "http://iiif.io/api/auth/0/login",
                        "label": "Archival material less than 100 years old",
                        "description": "This digitised archival material requires acceptance of the Wellcome Library's terms and conditions...",
                        "service": [
                            {
                                "@context": "http://iiif.io/api/auth/0/context.json",
                                "@id": "http://wellcomelibrary.org/iiif/tokenterms",
                                "profile": "http://iiif.io/api/auth/0/token"
                            },
                            {
                                "@context": "http://iiif.io/api/auth/0/context.json",
                                "@id": "http://wellcomelibrary.org/iiif/logout",
                                "profile": "http://iiif.io/api/auth/0/logout",
                                "label": "Log out of Wellcome Library",
                                "description": "Log out of Wellcome Library"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    "on": "http://wellcomelibrary.org/iiif/b17564980/canvas/c0"
}
```

The UV will always favour the actual auth service that is asserted in the info.json for an image service,  when it comes to load it properly. But it could use the one asserted in the manifest to make decisions about highlighting parts of the UI, requesting thumbnails etc.

However, this would very quickly result in a bloated manifest - if that auth block were repeated 1000 times. But this is JSON-LD, it's a graph - we've made the statements once, we don't need to keep reasserting them all, we can thereafter refer to the auth services by @id alone:

```
{
    "@id": "http://wellcomelibrary.org/iiif/b17564980/imageanno/391fb5ab-6092-429f-9b91-e4c74de4c24a",
    "@type": "oa:Annotation",
    "motivation": "sc:painting",
    "resource": {
        "@id": "http://wellcomelibrary.org/iiif-img/b17564980-0/391fb5ab-6092-429f-9b91-e4c74de4c24a/full/!1024,1024/0/default.jpg",
        "@type": "dctypes:Image",
        "format": "image/jpeg",
        "height": 1024,
        "width": 683,
        "service": [
            {
                "@context": "http://iiif.io/api/image/2/context.json",
                "@id": "http://wellcomelibrary.org/iiif-img/b17564980-0/391fb5ab-6092-429f-9b91-e4c74de4c24a",
                "profile": "http://iiif.io/api/image/2/level1.json",
                "service": "http://wellcomelibrary.org/iiif/accepttermslogin"
            }
        ]
    },
    "on": "http://wellcomelibrary.org/iiif/b17564980/canvas/c0"
}
```

This is exactly the same statement as the first chunk of JSON, but it relies on the UV already having seen the expanded version of ```"service": "http://wellcomelibrary.org/iiif/accepttermslogin"``` earlier in the manifest. Now although the manifest is a graph of RDF, the UV isn't processing it in those terms and neither will most other clients - it's just JSON. Hence https://github.com/UniversalViewer/universalviewer/issues/186. 

In none of what we've seen so far is an auth service asserted on the manifest resource itself - always on an image service. That is, there's nothing equivalent to

```
<my-manifest>  svcs:has_service  <my-login-service>
```

If you've been looking at Wellcome Library manifests you'll have seen auth services attached to various other resources. This is by and large a leftover from experiments with having a special location that the UV could look for the full auth service declaration rather than traversing the manifest to find it, but it's semantically wrong - we don't want to assert the triple above, because we're not interested protecting the manifest itself (and we're not enforcing it anyway). If we did assert that triple on the manifest then we would expect the client to negotiate the auth workflow when requesting the manifest itself, which is a valid use (and sounds like yours) but is not what the UV is doing.

Apologies for taking my time getting here:

> So UV doesn't use the presentation API's auth at all?

Answer - not for access control on the Presentation API resources. Not **yet** anyway.

Right now I'm writing up implementation notes for the IIIF Auth API. Perhaps you'd like to review them next week?

**Comment by edsilv** [comment]
closing this unless there are any objections?
