### ISSUE TITLE
Expanded thumbnail view performance, Firefox especially

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#262]
This manifest has 1003 canvases:

http://wellcomelibrary.org/item/b21274344

In Chrome (48.0.2564.116, Windows 10) the expanded thumbs view takes about 3-4 seconds to render (on a fast PC).

In Firefox (44.0.2) the expanded thumbs never load, and the browser warns the user about an unresponsive script. 

Internet Explorer (Edge, 20.10240) does persevere and eventually renders the expanded thumbs after about 30-40 seconds.

This performance is consistent with other manifests of this size. Although they use different JS engines the performance of these browsers is not so different as to explain this purely in terms of engines - Firefox in particular is very quickly getting itself tied in knots rendering the resized thumbs:

![firefox-uv-thumbs](https://cloud.githubusercontent.com/assets/1443575/13728317/17fc2fe4-e90c-11e5-90e8-a41b05e00520.png)

**Comment by edsilv** [comment]
The cause of the crash was the thumb resizing operation. Every time the user scrolls or changes the size of the thumbnails, _every_ thumb was being resized, which was timing out in Firefox.

The resizing function is otherwise performant, it's just that resizing a lot of thumbnails was (I think) causing too many layout reflows.

To break up the thumbnail resizing into manageable "chunks", I've added three new config options to contentLeftPanel:

- `galleryThumbChunkedResizingEnabled` (default: true) 
- `galleryThumbChunkedResizingThreshold` (default: 400)
- `galleryThumbLoadPadding` (default: 3)

I tested 

http://universalviewer.io/examples/?manifest=http%3A%2F%2Fwww.qdl.qa%2F%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9%2Fiiif%2F81055%2Fvdc_100000004987.0x000001%2Fmanifest

with a threshold of 500 and this was still crashing Firefox, so I set the default threshold to 400, which it can cope with.

This means that if a manifest has over 400 pages, the gallery chunks the resizing operation to only the visible rows, plus/minus `galleryThumbLoadPadding` * the thumb height.

This means that < 400 page manifests like the Biocrats are unaffected.

When in chunked mode, thumbnails outside the visible area are hidden - this is to avoid unsightly mixed-sizes after changing the size of the thumbnails. They are only shown when in the visible area and post-sizing.

This seems to work well, except in edge-casey scenarios where you scroll to the bottom and load thumbs at their initial size, then scale the thumbnails down, and scroll back to the bottom, then gradually scroll upwards. The scroll position jumps as the size of the scroll content changes. I don't think there's an obvious solution to this problem, and is why I've made chunking configurable.

Deploying institutions may decide that they always want a consistent user experience and can set `galleryThumbChunkedResizingThreshold` to `0` - thus making every manifest have chunked thumbnail resizing.
