### ISSUE TITLE
language choice forgets former locale

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#265]
I created a locale for Dutch from the source files, run grunt, and referred to it in the attribute "data-locale":
```
http://shared.ugent.be/viewer/archive.ugent.be%3A082FD364-C35A-11DF-A9D6-99EF78F64438
```
The locale nl-BE:
```
http://shared.ugent.be/js/uv/lib/uv-seadragon-extension.nl-BE.config.json
```

It works, but when you switch to another language, the option "Nederlands" disappears.
When I look at the build locale for en-GB, I see that the attribute "localisation" only
contains the two default languages (English and Welsh):
```
http://shared.ugent.be/js/uv/lib/uv-seadragon-extension.en-GB.config.json
```

Any idea?

**Comment by edsilv** [comment]
Hi, apologies for the delayed response...

I've written up the steps for creating an nl-BE translation here:

https://docs.google.com/document/d/1SJm4G6twYTquLUb5nIE6gZbpzfQcvDTBFToq6a9P_-w/edit?usp=sharing

You will need access to transifex - I should just need your email address for that. I'll create an nl-BE translation for you to enter your text.

I think the problem you're seeing might be because there is no corresponding nl-BE.json _config_ file.

**Comment by nicolasfranck** [comment]
Thanks, I'll have a look at it.

**Comment by LlGC-szw** [comment]
Thanks Ed that's really useful for us too.

**Comment by nicolasfranck** [comment]
my email address is nicolas.franck@ugent.be

**Comment by edsilv** [comment]
@nicolasfranck you should receive an email invitation

**Comment by nvanderperren** [comment]
Hi, I was wondering if the Dutch translation is added? (Can't find it in the code and the viewer of the UGent has no Dutch translations (https://lib.ugent.be/viewer/archive.ugent.be%3A4F68A2B0-4685-11E1-88B2-EC653B7C8C91#?c=&m=&s=&cv=&xywh=1610%2C-161%2C4851%2C2481). 

Otherwise, I would like to translate it to Dutch.

**Comment by nicolasfranck** [comment]
@nvanderperren I once started a translation, I think it was in transifex or something like that, but never finished it ;-)

**Comment by nvanderperren** [comment]
Okay, thanks @nicolasfranck, I'm going to take a look at it.
