### ISSUE TITLE
Canonical links

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#270]
How can we get the UV to display canonical links for sharing? Hash parameters are sometimes useful and sometimes problematic in this context.

**Comment by jennpb** [comment]
This is something that I would like to see some proposed solutions for.

Here are two of our use cases:

**1. User wants to share a link to this whole item, or to cite this item in a bibliography.**
The permalink/canonical link could be clean and simple, e.g. wellcomelibrary.org/item/b123456 (or a shortened version, e.g. well.me/item/b123456)

**2. User wants to share a link to a specific state, like a zoom level, page number, etc**
The link should include hash params, BUT ONLY if the UI indicates to them that that is what is being shared.

**3. User wants to share a link to a specific state, like a zoom level, page number through social media**
The problem with this is that any side using Open Graph metadata will cut off all hash params, so even if you think you're sharing an opening to a particular page, or a zoom, the third party site will strip it, resulting in only the first image in the asset sequence (typically a book cover) is displayed!

**Comment by demiankatz** [comment]
All of these things make sense from Villanova's perspective as well, with a particular focus on use case 1; specifically, there have been complaints related to the fact that the hash parameters instantly appear on the address bar whether or not the user interacts with the viewer in any way, which is an impediment to copying and pasting a clean URL. We expose a "permanent URL" link in our metadata through our manifests, but even if a user clicks on that with the intent of copying it, they can't avoid the hash parameters. (Of course, a right click and "copy link" solves the problem -- but not everybody does that).

**Comment by tomcrane** [comment]
See https://github.com/UniversalViewer/universalviewer/issues/248

**Comment by tomcrane** [comment]
Here's a (possibly straw person) suggestion, that might solve several of these issues.

We don't update the actual URL of the page as the user does things, as we'd end up with a multitude of different URLs for the same resource, hurting SEO. So we update the #fragment, to support deep linking.

This has pros and cons, as discussed above.

I suggest some new configuration options that allow:

* always display hash fragments
* only display fragments when the state changes AFTER the initial state (#248)
* never show hash fragments
* Append deep link parameters as proper query string parameters in the "share" link in the sharing (embed) menu (default must be false)

![embded](https://cloud.githubusercontent.com/assets/1443575/14645766/e15befe6-064e-11e6-9280-d71d4797b913.png)

This dialogue does two different things - it offers a sharing link, and it offers the embed code. The sharing link will work fine when someone uses it directly, but if you mention it on Facebook, the thumbnail used won't be the page the user was looking at, it will be the thumbnail the containing page offers in its open graph image meta tag. If the containing page can support it, and if the institution is prepared to handle it, they can make the UV append the parameters to the sharing URL as actual query string params (i.e., a different URI - it would look the same but the # would be missing). An institution would have to understand what they need to support if they enable this option. The containing page could generate a new response that includes the correct thumbnail as the open graph image - and here's where it gets clever (I hope). 

To avoid the SEO problems, the server should only serve this special page to crawlers it can identify - e.g., using with the user agent facebookexternalhit/1.1 (https://developers.facebook.com/docs/sharing/webmasters/crawler) and similarly for other known open-graph-consuming user agents that are definitely NOT humans with browsers. If it's in any doubt that it is NOT an out of band OG request, it should redirect the response to the canonical page (301) and append the hash params instead of query string params, so that humans see a deep-linked version. The UV can remove the hash params once it has processed them. This should avoid the SEO damage that would be otherwise caused. Institutions can tailor the open graph response to return whatever image is appropriate for the params.

This is quite a lot of work for the containing page to do. If they are prepared to do it they could set the UV to "never show hash params" and "use real query string params in share URL" and handle the consequences.

@jennpb fyi

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
Closing as https://github.com/UniversalViewer/universalviewer/issues/462 is fixed
