### ISSUE TITLE
Problem with hierarchical archival collection in UV

### ISSUE THREAD

**Issue by glenrobson** [UniversalViewer/universalviewer#312]
I'm trying to show a hierarchical archival collection in the UV:

http://universalviewer.io/?manifest=http%3A%2F%2Fdams.llgc.org.uk%2Fiiif%2Farchive%2F3975658%2Ffonds.json#?c=0&m=0&s=0&cv=0&z=-0.6798%2C-0.0788%2C2.3596%2C1.5754

The first top level collection seems to show OK and the first sub collection series also shows and allows you to navigate between manifests. The problem seems to be the 2nd, 3rd and 4th items of the top level collection. When you click on them I would expect them to expand but currently when you click on them nothing happens. At the moment the collection is linked together with collections + manifests fields but when #291 is supported Ill change it to members as there are some levels which contain child manifests and collections at the same level. 

http://dams.llgc.org.uk/iiif/archive/3975658/fonds.json

I'm sorry if its a problem with the mainfests/collections but I can't spot it and there aren't any errors in the javascript console I can see.

Thanks for your help

Glen

**Comment by edsilv** [comment]
This appears to have been remedied slightly by: 

https://github.com/UniversalViewer/universalviewer/pull/308 

and possibly

https://github.com/UniversalViewer/universalviewer/issues/286

 Although it's still not right... 

Cardiganshire Appeal Tribunal > Clerk of Tribunal's notebooks

appears twice.Clicking on it loads the tree at the new collection, without preserving the parent. We need to improve the collectionIndex to be a comma separated list instead of a single integer:

https://github.com/UniversalViewer/universalviewer/issues/313

@demiankatz

**Comment by edsilv** [comment]
@glenrobson please see #329
