### ISSUE TITLE
Valid manifest crashes universalviewer.io

### ISSUE THREAD

**Issue by jcoyne** [UniversalViewer/universalviewer#317]
When I put this url in the field: https://gist.githubusercontent.com/jcoyne/78db6cfb554d6c5b120c39260ea609f5/raw/6ee86534f2208f32cdc9522b8cf2dccd3b0f3582/manifest.json  and click "Open"

Nothing displays and I see this in the console: `TypeError: p is undefined`

<img width="712" alt="screen shot 2016-05-12 at 3 10 19 pm" src="https://cloud.githubusercontent.com/assets/92044/15228823/b0fbf21c-1853-11e6-9076-e2a3285a077d.png">

The IIIF validator thinks this is valid though.

http://iiif.io/api/presentation/validator/service/validate?url=https%3A%2F%2Fgist.githubusercontent.com%2Fjcoyne%2F78db6cfb554d6c5b120c39260ea609f5%2Fraw%2F6ee86534f2208f32cdc9522b8cf2dccd3b0f3582%2Fmanifest.json&version=2.0&format=html

**Comment by jcoyne** [comment]
I think this is because the manifest didn't have a service. When I added one it gets past this error. It might be a good idea to trap for this error and log something more user friendly.

**Comment by edsilv** [comment]
Yep, this was a problem in manifesto (the base IIIF utils lib that the UV uses). I've altered it so that if it can't find the image service it returns the thumbnail or null, but doesn't error out:

https://github.com/UniversalViewer/manifesto/blob/dev/src/Canvas.ts#L48

The problem then is that without the image service OpenSeadragon can't find the tiles. This shows a user-friendly error though.

Here's an example of a working level 0 manifest for reference:

https://ipfs.io/ipfs/QmYomyCpT1vKNovYvTjAStYq31JoaH8xdivjmWcDj5mpM1

**Comment by jcoyne** [comment]
Thanks!
