### ISSUE TITLE
Use withCredentials for info.json requests to allow authentication/authorization scenarios

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#33]
https://github.com/openseadragon/openseadragon/issues/543

**Comment by edsilv** [comment]
http://image-auth.iiif.io/api/image/2.1/#authentication

**Comment by tomcrane** [comment]
Here’s a good test case for this.

1 Visit any archive on the wellcome library – e.g., http://wellcomelibrary.org/player/b1818893x. Accept terms. This is so you have an active session.
2 Now (within a few minutes of 1) load the same manifest into the UV: http://universalviewer.azurewebsites.net/?manifest=http://wellcomelibrary.org/iiif/b1818893x/manifest
3 The info.json request that OpenSeadragon is making fails (returns 401) but if you request it directly you can see that it returns a 200: http://wellcomelibrary.org/iiif-img/b1818893x-0/e100fbe3-5f1c-49b7-a6ce-7bf82be23c1e/info.json
4 This is because OpenSeadragon is not sending the cookie you acquired at step 1, it needs ajaxWithCredentials: true on the OpenSeadragon object.

**Comment by tomcrane** [comment]
This issue is redundant as the new auth model avoids sending info.json requests with credentials.
