### ISSUE TITLE
Remove directory "dist" from git

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#342]
I wonder why the directory "dist" is present in the git repo,
if one can create this from the source files. This makes
pull requests heavier.

Add it to the .gitignore?

**Comment by edsilv** [comment]
This is so that when using npm or bower install there are built files available in /dist.

The workflow I've arrived at is to use github URIs in package.json wherever possible rather than using the npmjs registry. This makes updating dependencies like manifesto and manifold pretty quick without having to publish releases.

This is convenient for smaller libraries, but perhaps I should start publishing more official releases for the UV in the manner OpenSeadragon does it:

https://github.com/openseadragon/openseadragon/releases

I think @iangilman is building to here:

https://github.com/openseadragon/site-build/tree/master/built-openseadragon/openseadragon

Then when publishing a release on Github, selecting these files via the user interface.

**Comment by nicolasfranck** [comment]
ok, sounds reasonable ;-)

**Comment by leigh-ols** [comment]
I wonder if this could be reconsidered?

In the case that someone wants to make minor modifications in a fork of the primary repository. Every time they try to rebase their fork with updates from master there are merge conflicts all over the place from the dist folder.

What should be a simple: 
`git pull && git checkout 'branch' && git rebase master`

Becomes much more of a hassle due to merge conflicts in what are ultimately built files. The average dev has no obvious reason as to why they are even in the git repository.

I understand there are reasons (as laid out above) for keeping the dist folder but considering it's widely accepted to be against best practices and so unexpected behavior to developers with little rhyme or reason. Perhaps it could be reconsidered?

**Comment by edsilv** [comment]
Yeah, I think as mentioned above we should be building to a separate repo as per openseadragon and linking to that in the releases.

**Comment by jrhoads** [comment]
+1

On a related note, the "Stable Builds" section of the README points to the Github Releases Page.  The most recent build is v1.6.14.

Are the 1.7.x and 1.8.x versions not considered stable?  Or has the preferred method for installation changed to npm/yarn/bower?

**Comment by edsilv** [comment]
Just to note that many small projects _do_ use a `dist` directory in this way, but the UV has too many assets really for it to be viable.

There is a stable v2.0 release planned for early next year. Things have been moving very quickly this year, but I hope to reign things in a bit in terms of planning and working towards official releases instead of reacting to project-specific requirements.

From now on all new work will be assigned specific issues and version milestones will be created with an associated project board:

https://github.com/UniversalViewer/universalviewer/projects

The preferred method of installation is now npm. I'll publish the v2.0 release to npm when ready. Bower support is being deprecated.

**Comment by edsilv** [comment]
Instead of using the examples sub repo to publish from, reintroduce the dist directory, gitingore it, and add a files entry to package.json:

```  
"files": [
    "dist/"
],
```

**Comment by sdellis** [comment]
For our particular situation, we are going to explore using Webpacker, a Ruby gem that allows us to circumvent the Rails "asset pipeline". We believe this may allow us to integrate our css/theming tweaks that require a rebuild to configure. If this works, then we may not need the pre-compiled `dist/` files.

However, publishing the compiled version would be good for a number of scenarios where devs might not be able to integrate the build process into their own environments, or they may simply want to include a script source that's hosted at a CDN or something. Also, the ability to configure not only features, but also the ability to override CSS without a rebuild might be helpful. The [pul_uv_rails](https://github.com/pulibrary/pul_uv_rails) gem was initially created because we were not able to make subtle CSS theming changes without rebuilding.
