### ISSUE TITLE
make place of buttons configurable

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#343]
Now these functions..
- image search ( prev, next buttons )
- change locale
- change page view
- bookmark
  ...

are attached to a specific panel (footerPanel or headerPanel),
and one does not need all of them. 

Would it be better to define these components, and make it possible
to add them to either footerPanel or headerPanel ( e.g. an attribute
like "components" that lists them)

```
"components":   ##["changeLocale","bookmark","imageSearch"]
```

That way one can add all of these components to the footer,
and choose not to use certain components. For now using
both panels takes up too much space if all of these components
can be merged in one panel. But that's of course case dependent.

Just an idea

**Comment by edsilv** [comment]
@demiankatz has expressed an interest in this kind of capability too. I'm not sure what the best way to approach this is yet. The first task I felt was to create "manifold" and a base-component library:

https://github.com/UniversalViewer/manifold
https://github.com/edsilv/base-component

This allows units of functionality to be separated from the UV, e.g:

https://github.com/edsilv/iiif-tree-component

Eventually I'd like all UI to be componentised and the UV itself to be a component comprising a thin shell extending a generic library with adaptive layouts, iframe embedding, and configuration/internationalisation support.

Perhaps instead of treating each button as a component, we group them by type, e.g:

**canvas-options-component**
- zoom in
- zoom out
- rotate

**display-options-component**
- one-up
- two-up
- grid (expand gallery)

**global-options-component**
- print
- download
- open
- feedback
- bookmark
- share

See https://github.com/UniversalViewer/universalviewer/issues/339 where I've suggested moving the rotate and zoom buttons to the header.

Not sure how settings (the cog) fits in to this... It's a global option, but it should be in the header, not footer. Perhaps it's just 'baked' in to the header panel...

Then in the UV config, the header and footer would have a `components` section like the one you specified:

    "components":   ["canvas-options-component", "global-options-component"]

**Comment by nicolasfranck** [comment]
:+1:

**Comment by edsilv** [comment]
Perhaps we make the components configurable like so:

```
"components":   [
    {
        name: "global-options-component",
        options: {
            settingsEnabled: false
        }
    }
]
```

The above would be for the footer where we don't want the settings icon.

**Comment by nicolasfranck** [comment]
Indeed. Doesn't matter how ;-)

Although, wouldn't that create a "breaking change", as one
cannot/should not support both old and new behaviour?

**Comment by edsilv** [comment]
There's a discussion [here ](https://github.com/UniversalViewer/universalviewer/pull/172) about how to make the config inherit from a global file.

If we implemented this, old configs could inherit from it and get the default components, therefore mitigating the breaking change?

**Comment by nicolasfranck** [comment]
We can indeed fill the "components" attribute with default components like they work now

**Comment by edsilv** [comment]
related: https://github.com/UniversalViewer/universalviewer/issues/319

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.
