### ISSUE TITLE
Viewer unable to locate embed.js

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#35]
Hello,

I've come across an issue when deploying the universal viewer. I built the viewer using Grunt instructions and tried to recreate the example on our server http:// serverName /universalviewer/examples/, but it won't run as the viewer is trying to use http:// serverName **/build/uv-1.0.48/js/embed.js?_=1429265822504** could this path be changed to be relative to where the viewer is deployed?

Thanks,
Dylan

**Comment by edsilv** [comment]
Hi,

I think the problem is with this line of examples.js:

https://github.com/UniversalViewer/examples/blob/master/examples.js#L795

What this section does is figure out if the examples are running on localhost or are deployed on a website. If on localhost, it appends the debug version of embed.js, which in turn loads the debug version of the UV with code sourcemaps.

Otherwise, it assumes the examples are deployed in the root of a website and appends the built version of embed.js.

You can see an example of deploying the examples to the root of a website here:

http://nlw.azurewebsites.net

If you open the examples.js on that site in chrome dev tools and set a breakpoint on line 720, you can step through and see what's happening.

Lines 733 to 743 are about rewriting paths in the embed code and examples app. You'll need to change them to:

    $('.uv').updateAttr('data-config', '/examples/', '/universalviewer/examples/');
    
    $('.uv').updateAttr('data-uri', '/examples/', '/universalviewer/examples/');
    
    $('#locale option').each(function() {
        $(this).updateAttr('value', '/examples/', '/universalviewer/examples/');
    });
    
    $('#manifest option').each(function() {
        $(this).updateAttr('value', '/examples/', '/universalviewer/examples/');
    });

You'll need to change the embed script path on line 745 to:

    $("body").append('<script type="text/javascript" id="embedUV" src="/universalviewer/examples/build/uv-1.0.47/js/embed.js"><\/script>');

**Comment by LlGC-dwj** [comment]
Hi Ed, thanks for the quick response, that cleared my problem.

**Comment by edsilv** [comment]
Cool, no probs.
