### ISSUE TITLE
previous/next result links should only show when there is a previous or next result to show

### ISSUE THREAD

**Issue by jronallo** [UniversalViewer/universalviewer#374]
This is with regards to the behavior of search inside pagination in UV 1.8.24.

If there is only one result, and you are on that result, then the links should not display (or should be grayed out).

If the user is viewing the last result, then the next result link should not display.

If the user is viewing the first result, then the previous result link should not display.

**Comment by edsilv** [comment]
I've fixed this as part of https://github.com/UniversalViewer/universalviewer/issues/367

See: http://nlw.azurewebsites.net/?manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb18035723%2Fmanifest

Try searching for "gene".

This is currently on the `pan` branch, but will be in `dev` soon.

cc @mialondon

**Comment by mialondon** [comment]
Thanks @edsilv ! It doesn't seem to take effect when search results first load, possibly because the user hasn't started navigating through the results yet? If the viewer knows your position in the item and whether or not there are search results either side of your position, it'd be great if it disabled next/previous as appropriate.

The zoom into the search result is cool but possibly set too deep - readers may prefer to see the highlighted word in context rather than filling the screen?

**Comment by LlGC-szw** [comment]
Ed's added in the ability to turn off the close-up zoom as part of the current NLW development so other institutions can turn that off if it's not suitable for their material.
