### ISSUE TITLE
Loading manifest with withCredentials

### ISSUE THREAD

**Issue by Edminsson** [UniversalViewer/universalviewer#378]
We need to load manifests with withCredentials. We could make changes in Manifolds bootstrap method in the Bootstrapper class and use an $.ajax call directly instead of using manifesto.loadManifest, like the call when msie==10. 
We could also change the interface in Manifesto to be able to make requests using withCredentials.
    interface IManifesto {
        loadManifest: (uri: string, withCredentials?: boolean) => Promise<string>;
    }
If we do a pull request for this feature which alternative would you prefer?

**Comment by tomcrane** [comment]
Hi @Edminsson 

Are you trying to protect the metadata in the manifest, or the images that the manifest points to? If the latter, you should leave the manifest open and protect the image service endpoints using the IIIF Auth API, which the UV supports (it doesn't yet support the draft 0.9.3 version, but will very soon). 

If you need to control access to the manifest itself (e.g., because its metadata is sensitive), as well as the image services it references, then the same pattern described in the Auth specification could be used. If the user has acquired a cookie then the UV, on encountering an HTTP 401 response for the manifest, could attempt an interaction with the token service provided in the manifest. The UV would need to support that, but given that it supports essentially the same interaction for info.jsons that would not be too difficult.

This authed-manifest use case has not been the priority because generally it's the pixels that are important, rather than the metadata about them in the manifest. As the same image services could be re-used in many different manifests, access control of the manifest is only important if the manifest JSON contains secrets.

Tom

**Comment by tomcrane** [comment]
For reference: http://iiif.io/api/auth/0.9/

**Comment by Edminsson** [comment]
Thank you Tom, we will take a close look at the IIIF Auth API and the implementation in UV to see if we can use it for our purposes. We are looking at protecting both the metadata about certain images and also the images themselves.

**Comment by Edminsson** [comment]
I'm wondering about a couple of things. 
The IIIF Auth API is currently not used when calling Manifold.loadManifest. Will this change in the near future? 
Also loadManifest uses jsonp for IE9 but IIIF Auth is relying on CORS and I assume it won't work on older browsers like IE9.

**Comment by tomcrane** [comment]
Hi @Edminsson  - no one has expressed the need so far for running loadManifest through the auth pipeline, but I think it would work. You would need to assert the auth services on the manifest.

I wrote a specific implementation note about the circumstances in which IE9 can work with the Auth API:

http://iiif.io/api/auth/0.9/implementation/#cors-and-xdomainrequest-in-ie-9-and-below

However, I would say that technically IE9 is NOT supported by the auth spec, because of these caveats. It's not truly interoperable if the spec allows for this. If an institution can ensure that the cross domain issues can be avoided, then it can use the UV in IE9 with the auth spec - but it will only work with the UV, and for the institution's own content - which is OK for lots of people.

**Comment by DavidWaldock** [comment]
At the risk of asking a daft question, how can you know about the
auth service if you can't load the manifest without using auth?

D

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.
