### ISSUE TITLE
make use of timestamp in iiif image request configurable?

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#431]
Every request to the IIIF Image API now includes the parameter "t", set to the current timestamp.

Is this to prevent stale cache entries? 

In my case, the proxy server nginx forwards the requests to the IIPImage Server. As requests can come in any form ( the iiif syntax with uses no url parameters, or the rewritten form for the iipimage server, which uses only url parameters ), I need to add the url parameters to the cache key. 

That's why the fastcgi cache never has a cache hit because the parameter "t" adds a unique value.

**Comment by tomcrane** [comment]
@fractos I think we are able to configure nginx to ignore just the t param for caching in the DLCS, can you share the details with @nicolasfranck?

@edsilv is the t param appended for the auth case where the initial request failed because of a 401, and the browser needs to be persuaded to issue a full new request?

**Comment by fractos** [comment]
@tomcrane @nicolasfranck  Hi, this is currently done by telling nginx that we don't include the query string as part of the proxy cache key:

```proxy_cache_key	$scheme$proxy_host$uri;```

**Comment by nicolasfranck** [comment]
I use the fcgi_cache_key, that works the same.
I think I solved it by changing:

```
fastcgi_cache_key "$scheme$host$request_uri";
```
into
```
fastcgi_cache_key "$scheme$host$uri";
```

Using $uri ( the rewritten URI ) instead of $request_uri ( the original URI ) was probably the key to solve this.

thanks!

**Comment by edsilv** [comment]
@tomcrane that sounds correct. Pretty sure it was auth-related.

**Comment by tomcrane** [comment]
I think the problem is that if you do this:

```
myImage.bind('error', function (e) {
        // need to do auth...
});
...
myImage.attr('src', 'http://example.org/thumb.jpg');
// fires error because 401
// do some auth.....
// OK, done auth, try again:
myImage.attr('src', 'http://example.org/thumb.jpg');
```

This doesn't work, because you're just setting the attr to what it already is - you haven't changed it so the browser doesn't re-request it. Therefore you add the ?t=timestamp to make the browser get the image again, which prevents it being cached when you really want it to be cached.

However, this works as well:

```
myImage.src = "http://example.org/thumb.jpg" + "#" + new Date().getTime();
```

I did this in my auth test harness and it triggers a reload of the image (the 'src' attribute has changed), but without sending a different URL to the server (the # is client only).

Worth a try, and would speed up the loading of the thumbs if this is the only reason for the "t" (it may not be...)

**Comment by azaroth42** [comment]
Depends if you're trying to avoid browser cache or server cache. The #fragment won't be sent to the server, and hence won't break caches along the way, but should trigger the browser to avoid its internal cache.  A query param will be sent everywhere, breaking all caches. Having this configurable seems wise, otherwise every image will be requested anew, every time... with terrible performance implications.

**Comment by tomcrane** [comment]
Demo - http://tomcrane.github.io/iiif-expts/cache/auth.html

![capture](https://cloud.githubusercontent.com/assets/1443575/23079243/fb8ca2f4-f543-11e6-8ed4-eb5965d04cff.PNG)

**Comment by ekilfeather** [comment]
For what it is worth this is the workaround we used on lighttpd to dwal with unwanted timestamp query
/etc/lighttpd/conf.d/iipsrv.conf

```
server.modules += ("mod_rewrite")

url.rewrite-once = (
    "^(.*)(?=(\?t\=[0-9]+))" => "$0"
)
```

**Comment by giacomomarchioro** [comment]
Hi, 
I am facing the same issue using iip image server with apache2 and nginx as proxy server and with enabled Fcgid.  I have tried to use the solutions proposed here but I still experience the same problem. Can you provide me with a hint for solving this problem?
Thank you.
Giacomo

**Comment by stephenwf** [comment]
@giacomomarchioro If you are able to change the configuration for the viewer you can switch off the time-stamps.

https://github.com/UniversalViewer/universalviewer/pull/585

Here's a direct link to the configuration:
https://github.com/UniversalViewer/universalviewer/pull/585/files#diff-51e87ee435f1a105ed3ddaf633bcfeaf60988b590a973f3c827551adb06e40b0R9

**Comment by giacomomarchioro** [comment]
> @giacomomarchioro If you are able to change the configuration for the viewer you can switch off the time-stamps.
> 
> #585
> 
> Here's a direct link to the configuration:
> https://github.com/UniversalViewer/universalviewer/pull/585/files#diff-51e87ee435f1a105ed3ddaf633bcfeaf60988b590a973f3c827551adb06e40b0R9

Thanks I solved it substituting all `thumbsCacheInvalidation":{"enabled":true` with `thumbsCacheInvalidation":{"enabled":false`  in all the config files. I post the sed command I used for reference:

`find ./ -type f -exec sed -i 's/"thumbsCacheInvalidation":{"enabled":true,/"thumbsCacheInvalidation":{"enabled":false,/g' {} \;`
