### ISSUE TITLE
Make it possible to expand multiple nested subcollections in index view

### ISSUE THREAD

**Issue by emmastanford** [UniversalViewer/universalviewer#446]
With nested ranges, it's possible to expand multiple sections in the index tree at once, so you can see all the bottom-level items simultaneously (for example, http://iiif.bodleian.ox.ac.uk/iiif/viewer/390fd0e8-9eae-475d-9564-ed916ab9035c). With nested collections, this doesn't seem to be possible. A plus sign appears only next to the currently selected collection, and if you click on a different collection to expand its subcollections, a) any other previously expanded collections collapse and b) the sidebar switches to thumbnail view, which takes a little while to load, and then you have to click back to index view in order to see the subcollections. That seems like too many clicks.

Example collection here: http://universalviewer.io/uv.html?manifest=http://wellcomelibrary.org/iiif/collection/b20417081

**Comment by edsilv** [comment]
Hi, this is because collections are "lazy loaded" unlike ranges which are all available once the manifest has loaded. Opening a collection re-bootstraps the UV, which is designed to only display individual manifests one at a time. What makes this more confusing is that the tree doesn't preserve your active selection between refreshes (https://github.com/UniversalViewer/universalviewer/issues/302).

One way to keep the tree view visible is to use the `defaultToTreeEnabled` and `defaultToTreeIfGreaterThan` config options on `contentLeftPanel`. Setting `defaultToTreeEnabled` to `true` and `defaultToTreeIfGreaterThan` to `1` will ensure that the UV always defaults to showing the tree.

Perhaps we should look at trying to load more of the collection items in the background to fill out the tree. Something @tomcrane, @demiankatz and others might like to discuss on an upcoming community call.

**Comment by edsilv** [comment]
@emmastanford I'm adding this to the agenda for the next UV community call on the 14th

**Comment by LlGC-szw** [comment]
The feedback we've had is that it you don't know there are items in the structure unless you click on them (eg https://journals.library.wales/view/4718179/4718621/0#?xywh=-1188%2C-203%2C4639%2C4043). We'll look at defaultToTreeEnabled but also happy to discuss to see what can be done without compromising loading times.

**Comment by edsilv** [comment]
Closing this as I think #515 now encapsulates it.
