### ISSUE TITLE
Add support for web components/polymer custom elements

### ISSUE THREAD

**Issue by colehansen** [UniversalViewer/universalviewer#469]
I'm working on a project to create Polymer custom elements that encapsulates universal viewer instance(s).

Example usage:
```html
<html>
<head>
    <link rel="import" src="[relative path]/universal-viewer.html">
</head>
<body>
    <universal-viewer uri="/path/to/manifest.json" width="700px" height="500px"></universal-viewer>
</body>
</html>
```
I have a working (proof of concept) implementation over at [universal-viewer](https://github.com/Brown-University-Library/universal-viewer). However, it required me to change the UV embed.js code.

After digging through embed.js, I noticed that the process of getting the embed script tag and the div.uv's relies on jQuery's $(selector) method. However, this won't find any elements inside the Shadow DOM. Once I changed the code to also search the Shadow Roots of the universal-viewer components, it was able to get it to work without much issue.

Given the increased usage of polymer and web components, I think this would be a valuable feature to add. Whether custom elements is something that UV wants to natively provide or leave it to third-party implementations could be discussed. Nonetheless, some code would need to be changed to allow either solution. I might be able to write a patch, but want to know the thoughts of the maintainers on this idea.

Issue #156 might be a step in the right direction, but I couldn't find a uv.js file in the v3 or component branch. So this issue could already be partly resolved depending on how that issue was solved.

**Comment by edsilv** [comment]
Really interested in trying to make the UV a custom element. Please check the v3 branch as a lot has changed in order to make the UV work as a component (https://github.com/viewdir/base-component). It would be great to get your thoughts on the components in https://github.com/viewdir that the UV is using (iiif-tree-component, iiif-metadata-component, iiif-gallery-component).

I see this as a first pass at componentisation. Have been looking at https://svelte.technology as a possible next step, although at the recent IIIF conference in Rome @pgte suggested using custom elements instead.

The last time I looked into Polymer I decided that it wasn't an option due to requiring IE11+. Unfortunately we have to support IE10+ right now. I think this is something that would bear discussion on the next community call.

embed.js is deprecated in the v3 branch, in favour of using a regular iframe with no cross-domain communication as per youtube etc. Here's where you can find uv.js:

https://github.com/UniversalViewer/examples/tree/66ae015c9368df35eaf1908d7b7b86f38d790452/uv

Everything is now being built to examples/uv instead of the dist folder (https://github.com/UniversalViewer/universalviewer/issues/342).

I will update npm to point to that once v3 is released.

Perhaps there's a way to make UV as a custom element an opt-in thing. Happy to help explore the possibilities.

**Comment by edsilv** [comment]
Just to give you an update on this, the IIIF Software Developers Group have created a survey which (among other things) will find out how many institutions require < IE11. 

The general consensus now is that web components are the way forward and if you don't want to use them there are perfectly good older versions of the UV you could use. Thinking that once UV v3 is released (some time this year) we can start looking at web components for v4.

Here's an interesting development in that space: https://github.com/ionic-team/stencil

It's a bit like svelte in that it's a compiler that produces "vanilla" javascript. Looking like a strong contender at the moment.

**Comment by edsilv** [comment]
Closing this as inactive. However, there has been some discussion on the UV Slack's #dev channel about stencil and web components. Please feel free to join. Also componentisation is on the agenda for the http://uvcon.io tech day.
