### ISSUE TITLE
'index' tab label

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#495]
Cross-posted from the UV slack... 

Revisiting an old issue that's become timely again - the 'index' tab label is confusing for people who expect a proper book-style index (e.g. https://wellcomelibrary.org/item/b19874844#?c=0&m=0&s=0&cv=0&z=-0.9562%2C-0.0772%2C2.9125%2C1.5433). Has anyone found a better label for this?

**Comment by mialondon** [comment]
Sections? Bits? Random parts?

**Comment by tomcrane** [comment]
This is not necessarily a problem to be solved by any code change, as the label already comes from configuration, so it is a UI decision for the BL what label to use. There is more we could do, though.

Possible options

1) Pick a word that is appropriate to any content - books, oral histories, operas, manuscripts, archive items, maps, newspapers... **Structure** is sufficiently abstract,  but may not be really suitable for any content. (NB `structures` is the name of the IIIF property being presented here - https://preview.iiif.io/api/image-prezi-rc2/api/presentation/3.0/#structures)

2) Allow the term for the tab to vary, so that it can say "Contents" or "Sections" or "Tracks" or "Index" or whatever term is appropriate for the structure being modelled. The UV already takes the term from config, from i18n files. So a page instantiating the UV could provide a content-specific label for structure.

3) As well as UV config, look for a suggestion for the label in the content itself, as an extension `structureLabel` property in the Manifest. This would obviously have no effect outside of the UV (unless other viewers like it and adopt it too). It also means the publisher of the content has to think about i18n of viewer interface, and not just of their published content. In this case the publisher of the content and the supplier of the viewer (i.e., on the web page, with config) are the same. 

1 and 2 are possible already. 2 also fits a more general pattern where the publisher who is aware of what a particular item is supplies a content-specific config file, not just setting the structure label but for other parts of the UI, the behaviour and appearance of the UV in general. E.g., the BL has UV newspaper config, UV printed books config, UV manuscripts config, UV maps config... and knowing what the item is, supplies one of these as appropriate, producing UI variations in the process.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by mialondon** [comment]
Is this a config option and has it been documented?

**Comment by demiankatz** [comment]
Superseded by #565.
