### ISSUE TITLE
Translations not working in metadata panel

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#519]
http://universalviewer.io/examples/#?c=0&m=0&s=0&cv=0&manifest=https%3A%2F%2Fedsilv.github.io%2Ftest-manifests%2Frange-renderings.json&xywh=-368%2C-728%2C4257%2C4993

**Comment by edsilv** [comment]
Do this first: https://github.com/UniversalViewer/universalviewer/issues/521

**Comment by tomcrane** [comment]
https://github.com/IIIF-Commons/iiif-metadata-component/blob/master/src/MetadataComponent.ts#L320

`getLabel` is using the right logic to pick the correct Welsh string because it's using Manifesto's `getLabel(..)`

... but at https://github.com/IIIF-Commons/iiif-metadata-component/blob/master/src/MetadataComponent.ts#L365 a different locale is introduced (not the ambient config/user locale). `_getItemLocale` can only ever return  `"en"` for the Title example above.

Which means this line then makes the wrong choice: https://github.com/IIIF-Commons/iiif-metadata-component/blob/master/src/MetadataComponent.ts#L372

So I guess the question is - why have `itemLocale` at all? Why not use `this.options.data.helper.options.locale` at line 372?

https://github.com/IIIF-Commons/iiif-metadata-component/blob/master/src/MetadataComponent.ts#L401 has the comment:

> // the item's label locale takes precedence

What was the reason for that? Maybe something to do with Princeton's showing all lang values option? The comment explains the bug but I can't see when that statement would apply.

**Comment by tomcrane** [comment]
![link to image in UV Slack](https://files.slack.com/files-pri/T06PSKEJX-F8WLF4N0L/image.png)
