### ISSUE TITLE
Internet Explorer compatibility issues

### ISSUE THREAD

**Issue by demiankatz** [UniversalViewer/universalviewer#54]
There seem to be two IE compatibility issues at the moment:

1.) The example is broken in IE8 because the jsoneditor.js script doesn't parse correctly. It appears that some work was done earlier to work around jsoneditor in IE8, but it looks like we're unconditionally loading the .js file, and that's stopping JS processing due to the parse error.

2.) Even if you work around the jsoneditor.js issue by directly accessing app.html without the framing example page, the images fail to load in IE8 and IE9 (putting the unhelpful message "error" into the JS console). This appears to be due to a 400 error from the image server, caused by requesting URLs like:

`http://wellcomelibrary.org/iiif-img/b18035723-0/ff2085d5-a9c7-412e-9dbe-dda87712228d/info.js`

instead of:

`http://wellcomelibrary.org/iiif-img/b18035723-0/ff2085d5-a9c7-412e-9dbe-dda87712228d/info.json`

This in turn seems (if I'm guessing correctly) to have something to do with this code:

<pre>
        if (!iiifUri){
            console.warn('no service endpoint available');
        }else if (iiifUri.endsWith('/')){
            if (!this.corsEnabled()){
                iiifUri += 'info.js';
            } else {
                iiifUri += 'info.json';
            }
        } else {
            if (!this.corsEnabled()) {
                iiifUri += '/info.js';
            } else {
                iiifUri += '/info.json';
            }
        }
</pre>

Perhaps this.corsEnabled is not returning the expected/appropriate value in IE8/9, but I don't know enough about what's going on here to speculate much further.

Also, on a side note, wouldn't this code be a bit more compact and readable as:

<pre>
        if (!iiifUri){
            console.warn('no service endpoint available');
        } else {
            if (!iiifUri.endsWith('/')) {
                iiifUri += '/';
            }
            iiifUri += this.corsEnabled() ? 'info.json' : 'info.js';
        }
</pre>
? I can submit a PR if you agree, but I haven't managed to figure out a good way to test this refactoring (which perhaps is a sign that I'm on completely the wrong track).

**Comment by edsilv** [comment]
Hi,

Try using noeditor.html instead of app.html for IE8, this excludes the editor script which cannot run in IE8.

corsEnabled uses Modernizr and the data-jsonp attribute to decide whether cors is enabled:

https://github.com/UniversalViewer/universalviewer/blob/6bcb0d41455f4834fc24474d307bb2b603a56b85/src/modules/uv-shared-module/baseProvider.ts#L119

modernizr should be doing its job correctly. You probably need to ensure that you have the jsonp checkbox checked in the examples (in the options directly under the viewer). This will set the data-jsonp attribute on the embedding div:

https://github.com/UniversalViewer/universalviewer/wiki/Embedding#data-jsonp

Yep, your code looks neater - submit a pull request and I'll merge.

I'm in Spain on holiday at the moment, so may not be able to respond very promptly on here.

**Comment by demiankatz** [comment]
First of all, thanks for getting back to me while on holiday! I was expecting to wait until your return before hearing back about this, and I'm certainly happy to wait for further communication on this issue.

Regarding noeditor.html, that does indeed help get IE8 to the same point of failure that IE9 currently demonstrates. Would it be worth linking to that from index.html so it's more findable?

Regarding corsEnabled, the problem appears to be that in IE<10, Modernizr.cors resolves to "false" which then means that the value of this.jsonp is irrelevant, since it's getting ANDed with false. corsEnabled will always return false, and thus resources will always be retrieved with the .js extension instead of .json, and thus the example fails. If I completely remove the Modernizr.cors check from corsEnabled and rely on the jsonp setting alone, then everything appears to work consistently in both IE8/9 and Firefox. However, I assume that Modernizr check was there for some reason, so I imagine that a full and proper solution may require a bit more subtlety. Any ideas? (I also note that the index page says "Default behaviour is to use JSONP for IE<10." -- perhaps that note is somehow related to this behavior).

Regarding the code optimization, see https://github.com/UniversalViewer/universalviewer/pull/55.

Thanks again, and enjoy the remainder of your trip!

**Comment by edsilv** [comment]
A link to noeditor.html could be a good idea. Perhaps alongside or underneath the "Config" heading under the UV.

Ideally I'd like to make index.html gracefully degrade for IE 8 and remove noeditor.html.

Regarding corsEnabled(), the logic goes:

If the browser supports CORS and the configuration isn't overriding this to use JSONP instead, use CORS (return true). Otherwise, use JSONP (return false).

This leaves the door open for cases where you may want to override a modern CORS-enabled browser to use JSONP instead.

| CORS supported  | JSONP disabled  | returns | 
|---|---|---|
| false  | false  | false | 
|  true | true  | true | 
|  true | false  | false |
| false | true | false |

So we can see from the table above that the only case where corsEnabled() returns true is when the browser supports CORS and JSONP isn't enabled in the config (which is most of the time). For IE < 10, CORS isn't supported, so corsEnabled returns false, defaulting to JSONP regardless of whether it's enabled in the config.

Hope this makes sense...! Struggling with it myself...

**Comment by demiankatz** [comment]
Regarding the graceful degradation of index.html, I think that conditional loading of jsoneditor.js (simply skip it in IE<9) might get us most of the way there. There seem to be a lot of different possible mechanisms for doing this sort of thing, though, and I'm not especially familiar with the field. If you have preferred libraries for browser detection / JS loading you'd be able to recommend, I can experiment further and see how far I get... but a little guidance would be helpful since I don't want to spend time learning/incorporating redundant tools if you've already got good candidates in place somewhere.

Regarding corsEnabled(), I agree that your logic table represents the current behavior of the code. But my observation is that with this current table, the viewer is broken in IE<10. If we change the last row of the table to return true instead of false, then IE<10 begins working. This seems to suggest that CORS detection is pointless (at least in the use case of the example). But maybe there are some other scenarios that break in the other direction, and that's why this is here in the first place. Regardless, we probably need to do something, since we have a major break and an apparent easy fix -- but it feels too easy, so I'm suspicious of it.

Actually, to take a step back, what is the significance of the use of info.js in the URI rather than info.json? In the IIIF spec (http://iiif.io/api/image/2.0/) there is no mention of info.js, and info.json is listed as a bright red "MUST." Is it possible the corsEnabled() behavior is fine but the real problem is that we should never be requesting info.js? Is this perhaps an off-spec feature of some specific image server that is not being used for the example?

**Comment by edsilv** [comment]
I'm using BrowserDetect for browser detection, and Modernizr for feature
detection.

https://github.com/UniversalViewer/examples/blob/master/utils.js#L51

In IE < 10 corsEnabled is correct to always return false regardless of
whether JSONP is enabled, meaning JSONP is used and info.js is requested
instead of info.json.

info.js is used for JSONP requests due to the way OpenSeadragon is set up:

https://openseadragon.github.io/examples/tilesource-dzi/ (see JSONP Request
for DZI JSON).

The example manifest urls won't work unless they're set up to support JSONP
- which they aren't. The British Library has a service endpoint with JSONP
enabled, but it's not publicly available yet. If you look in here:

https://github.com/UniversalViewer/examples/tree/master/manifest

These should all have JSONP "manifestCallback" wrappers. Try pasting those
into the manifest input field to test in IE < 10.

**Comment by demiankatz** [comment]
Great, I'll see what I can do about bypassing jsoneditor.js next week. Do you have a preferred technique for dynamic script loading?

Thanks also for the clarification on .json vs. js. But the point that's still confusing me is that, if we need to switch to JSONP when CORS is unavailable, how is it working in IE9 (and IE9 w/ IE8 compatibility) when I simply switch .js to .json in the code? Perhaps it has something to do with the discussion here:

http://stackoverflow.com/questions/12296910/so-jsonp-or-cors

which suggests that IE8/9 do handle CORS, but in a limited way. Perhaps it works well enough for the needs of UV.

**Comment by demiankatz** [comment]
I just did a quick bit of experimentation to see if I could use BrowserDetect to bypass jsoneditor.js, but there are actually two problems: first of all, BrowserDetect seems to be incapable of detecting the version for IE8 or IE9, at least on my system -- it detects 'Explorer' but the version is unknown. Secondly, based on the order of script loading, it appears that BrowserDetect is currently loaded AFTER jsoneditor, so we might have a chicken and egg problem.

**Comment by demiankatz** [comment]
One more thought on the CORS/JSONP issue -- is part of the problem here that the configuration is not sufficiently expressive? Right now, we basically have two settings: autodetect, or force JSONP. Could we also add a force CORS setting, for cases where we know JSONP won't work and we're willing to take our chances with bad browser behavior? That seems to be the best bet for my current use case, and it would be nice to be able to try this without having to hack the core code.

**Comment by edsilv** [comment]
I use require.js for dynamic script loading:

https://github.com/UniversalViewer/universalviewer/blob/master/src/extensions/uv-seadragon-extension/extension.ts#L233

I'm not sure why CORS is working for you in IE < 10 - perhaps it's because you're running the example locally?

Strange that BrowserDetect isn't detecting the version. Did you say previously that you were on Ubuntu? Perhaps the headers are different for your OS and BrowserDetect doesn't support them...

So the current behaviour is to always use CORS unless JSONP is forced or required for IE < 10. What if to force CORS in IE < 10 we just set data-jsonp="false". If it's "undefined" it automatically falls back to JSONP. If it's "false" it's specifically disabling JSONP.

**Comment by demiankatz** [comment]
Thanks, I'll take a look at require.js.

I'm not running the example locally, so that's not the explanation for things working. I'm running the viewer on my test server, the manifest is pointing at a separate image server, and I'm accessing the viewer from my desktop, so there are at least three different computers involved in the transaction!

Regarding BrowserDetect, my test server runs Ubuntu, but my desktop is Windows 7. Not sure why I'd be sending unusual headers. I am actually running IE9 and using compatibility mode for testing IE8, so maybe that's part of the problem... but I'd at least expect IE9 running in its native mode to report the right thing!

In any case, I like your suggestion regarding data-jsonp. I'll see if I can implement that on Monday and then all test this all again just to be sure I'm not crazy!

**Comment by demiankatz** [comment]
Okay, I have opened https://github.com/UniversalViewer/universalviewer/pull/62 and https://github.com/UniversalViewer/examples/pull/2 to implement the JSONP/CORS/autodetect switching we discussed. Sure enough, when I set this to "force CORS" mode, the standard example works correctly in IE8 and IE9. IE8 still puts a warning in the console based on problems with jsoneditor.js, so it would still be nice if we could detect the version and gracefully degrade; however, this warning does not prevent the viewer itself from working, so the problem is less serious than I had originally believed.

Please let me know if you'd like any more information from me, or if I can do anything more to help. For my purposes, if you are able to merge my PR's, I think I'll be able to adequately support IE for my users and would be content to see this issue closed.

**Comment by edsilv** [comment]
That's great, have merged your changes. Will close this. I've opened https://github.com/UniversalViewer/universalviewer/issues/64 as an enhancement.
