### ISSUE TITLE
IIIF :: Only JPEG output supported

### ISSUE THREAD

**Issue by stephanpauls** [UniversalViewer/universalviewer#554]
Hi

When i try to open a manifest file in the universal demo viewer 'https://universalviewer.io/uv.html', the thumbnails are not opened.
The error that i got is: 'IIIF :: Only JPEG output supported'

The url is https://services.libis.be/iipsrv/iipsrv.fcgi?iiif=/operational_storage/storage1/2017/12/07/file_56/V1-FL10046119.jp2/full/90,/0/default.jpg?t=1520258543365

If the t=1520258543365 is removed the url shows a thumbnail though.
The t=... is added by the universal viewer itself.

Stephan pauls

**Comment by stephanpauls** [comment]
Sorry , i have detected that it' s the same issue as #537

**Comment by tofkamp** [comment]
I found the same bug. The default documented installation of IIPserver on lighttp, can be used to display zoomable images with the option ?IIF=path/to/picture.jp2.
The universal viewer puts a "/full/90,/0/default.jpg?t=1521208380748" behind the url of the image in order to get the thumbnail. If you omit the ?t=... or replace it with &t=1521208380748, it works fine. Because the installation with debian+iipserver+lighttp+universal viewer is a good and simple one, a lot of people will/have found this bug.
A rewrite rule will help, but costs cpu cycles, which could easily be avoided. Please add an option to the config to switch between the two possible way of calling the IIIF server.
BTW The manifest editor shows correct thumbnails (http://iiif.bodleian.ox.ac.uk/manifest-editor/), but the UV is not.

**Comment by tomcrane** [comment]
I think this issue is better dealt with by solving this one:

https://github.com/UniversalViewer/universalviewer/issues/431

i.e., prevent the UV adding a timestamp, rather than making the UV support image service URLs that are not compliant with the IIIF spec.

**Comment by tomcrane** [comment]
(or by implementing timestamps as my suggestion here - https://github.com/UniversalViewer/universalviewer/issues/431#issuecomment-274100861)

**Comment by tomcrane** [comment]
The UV would then probably work with IIPImage's non-standard, unproxied URLs, but as a side effect, without having to explicitly accommodate them, which I don't think it should.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity. Cannot reproduce due to linked manifest being inaccessible.
