### ISSUE TITLE
public function to set an auth token

### ISSUE THREAD

**Issue by eroux** [UniversalViewer/universalviewer#624]
it would be important for our workflow to be able to set the auth token that's sent in the http headers by UV so that we can give it the token if we know it in advance (before creating UV). The typical workflow for us would be:

- user goes to our web app
- user logs in and web app gets a token
- user goes to a page where some iiif is displayed
- web app creates a UV instance and passes the token to UV

it seems to me like it could be a quite common workflow... is this something that could be done? If a PR could be accepted I'm ready to create one, what file would this have an impact on?

As a note, we also want to use IIIF Auth API. So there might be a second optional argument to this function that would be the token service it's associated with... would that be reasonable?

**Comment by tomcrane** [comment]
Hi @eroux - this scenario (in terms of user experience) is covered by the _External_ auth pattern as defined by the IIIF Auth Spec. The slight difference from your description is that the UV acquires the token itself, by the token service, but it knows that it is supposed to do that because the IIIF resource has an explicit `external` service on it. What _is_ done ahead of time is the setting of the cookie that the UV uses to acquire the token.

The user experience is the same, but the token isn't passed into the UV. The web site just needs to ensure that the user has acquired a _cookie_, e.g., by logging in.

https://iiif.io/api/auth/1.0/#external-interaction-pattern

https://iiif.io/api/auth/1.0/#workflow-from-the-browser-client-perspective

And here's a demo to illustrate the flow.

In this scenario, it's expected that you're going to arrange to have the user log in before they attempt to actually look at any IIIF content.

> * user goes to our web app
> * user logs in and web app gets a token

Here's the login page:
https://iiifauth.digtest.co.uk/external-cookie/05_cader_idris.jpg
The credentials are username/password (yes, those strings!)
This means we now have a **cookie**, not a token.
The post login screen here doesn't do anything. But on your site you'd then let the user navigate to your object web page.

Here's the manifest:
https://iiifauth.digtest.co.uk/manifest/05_external

And here's the info.json it points to:
https://iiifauth.digtest.co.uk/img/05_cader_idris.jpg/info.json

Note that the auth service has the external profile. It could have others too, to support multiple interaction patterns.

> * user goes to a page where some iiif is displayed

http://universalviewer.io/examples/#?manifest=https%3A%2F%2Fiiifauth.digtest.co.uk%2Fmanifest%2F05_external

> * web app creates a UV instance and passes the token to UV

Instead, web app creates a UV instance and doesn't need to do anything else! UV already knows what to do.

If for some reason you could get to the UV page without logging in, then the UV (in the absence of any other auth interaction patterns in the info.json) would just show an error meesage - you can verify this by clearing your cookies, or opening an anonymous session, and visiting the UV again.

**Comment by eroux** [comment]
I see, thanks a lot! Just to be clear: we're not using cookies at all (and we don't want to), that's what confuses me a little bit...  we store the token in localStorage. So with what you said, I think our workflow for logged users will be:

- user is on our website, say `example.com`
- user logs, token is in localStorage
- web app creates UV
- UV receives a 401, goes to the token service, `example.com/iiiftoken`
- the token service looks for the token in local storage (which will be shared as it's on the same domain) and returns it through the postmessage api

that would work right? 

Maybe the iiif auth spec could insist less on the term cookie? I think that's what confused me...

**Comment by eroux** [comment]
I've been thinking about it a bit more, and I believe there is still a problem, which is the discrepancy between logged and unlogged users.

The case of logged users is nicely handled by the `external` profile, I agree. But in this profile, users cannot log in if they haven't yet.

For the case of unlogged users, the login profile is still necessary (because they need to login). But the server cannot know when to send external or login... so I still don't know how to have a nice login workflow without this function... unless there is something I missed?

**Comment by eroux** [comment]
So, here's my understanding now:

## Current behavior
### Option 1: external profile
##### logged in user

in this case, UV will just use the token endpoint and retrieve the token. It's working fine.

##### non logged in user

in this case the token endpoint will say that the user is not logged, UV will not know how to log the user in and the access will fail, which is not OK

### Option 2: login profile
##### logged in user

in this case UV doesn't know that the user is already logged in so it will prompt the user to log in again, which is not OK

##### non logged in user

in this case UV will also prompt the user to log in, which is fine

## Wanted behavior
##### logged in user

I want UV to know that the user is already logged in and not to ask the user to log in again (as in the `external` profile)

##### non logged in user

I want UV to prompt the user to log in (as in the `login` profile)

---

am I right in my analysis? How can I get the behavior I want, which seems a relatively simple use case?

**Comment by tomcrane** [comment]
I think the answer is to use both. The UV will try external first, then move to the login interaction pattern if that fails.

About the naming of the cookie service - while other criteria could be used for authorising a web request (such as IP restrictions), the cookie service is so-named because many more complex forms of token based auth are not possible for simple web requests, such as the `src` attribute of an `img` tag. 

How are you controlling access for direct image API requests in your model?

For example

```
<img src="https://example.org/images/iiif/my-image/full/full/0/default.jpg" />
```

**Comment by eroux** [comment]
moving to https://github.com/IIIF/api/issues/1732
