### ISSUE TITLE
importing universalviewer in React

### ISSUE THREAD

**Issue by berger-n** [UniversalViewer/universalviewer#650]
Importing module in React results in an error:
``Module not found: Can't resolve 'universalviewer'``
(which seems logical regarding the file structure of the module itself)

Is there a better way to make it work than the postinstall workaround described [here](https://github.com/joelcrawford/uv/blob/dffc4f9ddc741634ae326846f40216837cafbcba/package.json#L12)?
Any plan regarding better React/ES6 support ?

**Comment by stephenwf** [comment]
You can use unpkg to check which files to import. The default `universalviewer/index.js` doesn't exist, which is why (using webpack?) you can't load it in in that way. 

Here's the link to the current version in unpkg: https://unpkg.com/universalviewer@3.0.16/

All the things you need to import are in the `/uv` folder, so these would be imports that look like:

```
import 'universalviewer/uv/helpers';
import 'universalviewer/uv/lib/offline';
import 'universalviewer/uv/uv.css';
import 'universalviewer/uv/uv';
```

There are no explicit exports, as the [helpers](https://github.com/UniversalViewer/universalviewer/blob/master/src/helpers.js) simply add global functions. You could take these functions and copy/adapt them. Once you've imported some files you'll be able to start bootstrapping the UV and its resources using the global `new window.UV()`

The main thing to mention is the `lib` files that go along with the UV. The UV uses requirejs to dynamically load in the parts it needs, and configuration. These files are expected to live somewhere in the root of the site it's hosted on (although that may be configurable). There will be a manual step of getting these assets hosted somewhere, and it may break encapsulation of React components, if someone where to pick it up and use it.

Hope that helped!

**Comment by berger-n** [comment]
ok thanks!
now it seems that `jQuery` version (2.2.1) conflicts with the one used int other modules (3.3.1)
is there a workaround for this?

**Comment by stephenwf** [comment]
You could try using [jQuery no conflict](https://api.jquery.com/jquery.noconflict/) in some way to avoid that issue.

**Comment by edsilv** [comment]
Here's an example of a next.js (react) site using the UV if that helps: https://github.com/nomadproject/nomadproject.github.io
