### ISSUE TITLE
Allow side panel expand/collapse animations to be disabled

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#756]
(WCAG 2.3.3)

**Comment by edsilv** [comment]
Add an option in settings to disable all UI animations?

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by LlGC-jop** [comment]
I think this has been done - it works for me when I select the reduced animations option and I couldn't find any animations other than the side panels:

The toggle() function in BaseExpandPanel checks for it.

The only caveat I can see is that if  `isFullyExpanded` is true i.e. the full expand button was clicked then the reduce setting wouldn't be checked, but as the full button is hidden by CSS, has no accessible content, and its tabindex is 0 I don't think anyone would ever be able to click it.

**Comment by demiankatz** [comment]
@LlGC-jop, I think the problem is that the setting is not currently respected by every extension. I agree that it works correctly in OpenSeadragon, but it does not appear to work in, for example, the PDF extension. See [the multi-PDF example](https://www.universalviewer.dev/#?xywh=-2323%2C-197%2C7214%2C3936&iiifManifestId=https%3A%2F%2Fdigital.library.villanova.edu%2FItem%2Fvudl%3A294631%2FManifest) for a demonstration of this -- the expand/collapse of both sidebars is animated regardless of the motion setting. The same is true of [this multi-part audio item](https://www.universalviewer.dev/#?xywh=-2323%2C-197%2C7214%2C3936&iiifManifestId=https%3A%2F%2Fdigital.library.villanova.edu%2FItem%2Fvudl%3A283833%2FManifest).

**Comment by LlGC-jop** [comment]
Hi @demiankatz 

I wanted to try and figure it out myself first, when you have a few mins free could you confirm my thinking please?

1. The reduce animations option checkbox is created in `uv-dialogues-module/SettingsDialogue.ts` so is available to all extensions.
2. When the box is checked/unchecked it calls `updateSettings()` which then 'publishes' `IIIFEvents.UPDATE_SETTINGS` which I'm assuming represents the name of an event.
3. The OSD Extension subscribes to that event and then in turn publishes `IIIFEvents.SETTINGS_CHANGE`, passing the settings through
4. `BaseExpandPanel.ts` subscribes to `IIIFEvents.SETTINGS_CHANGE` and sets `this.reducedAnimation` accordingly.

So in the short term to get other extensions to work the same they would simply need to do `3` so that the expand panel picked it up?

If that sounds about right I'll have a look again on Monday to make sure all the extensions work. Unless we want to just disable animations outright to simplify things?

**Comment by demiankatz** [comment]
@LlGC-jop, I haven't worked with this code before either, so I can't claim to have deep knowledge, but I believe that your assessment is correct. It feels like there ought to be a better way to do this than copying and pasting event handling logic into every extension, but that's probably the most pragmatic/least controversial approach for now.

(I don't have strong opinions about whether or not to disable animations globally, but since that would be a bigger change than just fixing this bug, it feels like it would require a separate conversation).
