### ISSUE TITLE
Pictures rotating when zoomed

### ISSUE THREAD

**Issue by EMAN-Omeka** [UniversalViewer/universalviewer#803]
Hello and thanks for the work on this project.

I hope it hasn't been reported yet ; I searched for '_rotation_' and '_orientation_' in the issue queue and didn't find anything relevant.

We use UV successfully in our project (thousands of pictures), but a bunch don't behave as usual : they appear OK at the default size, but **rotate 90 degrees when zoomed two steps**.

Examining the pictures, we found they embed the **EXIF** field "**Orientation**" which is set to 6 (90° reverse-clock rotation, which matches the rotating problem). 

We tried to blank this property with a command line utility, but then the pictures appear rotated by default, without even zooming.

My questions are : 

- is this a known problem ? 
- is there a parameter somewhere in UV that would correct this behaviour ?
- if not, what are the possible solutions, given we can do whatever we want to the pictures metadata-wise (for example, if there a value for the property which would solve the issue - I didn't find one) ?
- we can always delete the info and rotate the pictures with a script involving ImageMagick but it's cumbersome and we'd rather try something less invasive.

Any hint would be greatly appreciated .

Thanks for reading and, again for this great tool.

**Comment by nicolasfranck** [comment]
This seems more like a "problem"  in the image server, rather than in the viewer. A viewer does not inspect the image data, nor does the api specify any attributes that shows that there is a rotation to do.

We had the same problem with that exif tag "Rotation". It is better to remove that exif tag, and "manually" rotate them, as not all offline viewers, or image servers or whatever do take these rotation into account. If you would take it into account, what should width and height be, for example? It just adds unnecessary complication, in my opinion.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.
