### ISSUE TITLE
Assertion failed: [Viewport._setContentBounds] bounds.height must be greater than 0

### ISSUE THREAD

**Issue by 404mike** [UniversalViewer/universalviewer#934]
**UV version:**

```
 universalviewer@4.0.16
```

**I'm submitting a:**

- [x] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

UV throws `Assertion failed: [Viewport._setContentBounds] bounds.height must be greater than 0` errors on version 4.0.16. See https://codesandbox.io/s/uv-4-0-16-q5tj5k

CORS error not related to UV.

**Expected behavior:**

It looks like this issue was introduced in https://github.com/UniversalViewer/universalviewer/commit/3a01c626b9a71daa3fa7eee685bb6b42ad3dc322 as the previous commit works fine, see https://codesandbox.io/s/uv-4-0-6-4j863r?file=/index.html

**Steps to reproduce:**

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by demiankatz** [comment]
Thanks for pinning this down, @404mike! Given that there aren't many actual code changes in the commit you highlighted, I suspect this is actually a problem introduced in either manifold 2.0.18 or manifesto 4.2.15, so we might have to investigate those projects and fix the problem over there. And actually, since manifesto's requirement was changed from the broad `^4.2.14` to the pinned `4.2.15`, I suppose there's also a possible scenario where a bug fixed in a later version of manifesto is reintroduced by forcing a rollback here.

@edsilv, what do you think? I'm unfortunately very short on time this week due to a conference and can't dig much deeper right now, but if any of my theories seem particularly likely or unlikely, let us know and it might help direct the course of further investigation.

**Comment by 404mike** [comment]
I'm going to close this ticket as I believe it is a similar issue to [913](https://github.com/UniversalViewer/universalviewer/issues/913)
