### ISSUE TITLE
PDFs no longer loading

### ISSUE THREAD

**Issue by 404mike** [UniversalViewer/universalviewer#939]
**UV version:**

```
latest
```

**I'm submitting a:**

- [x] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

The UV has hardcoded a dependancy to Mozilla pdf.js - see https://github.com/UniversalViewer/universalviewer/blob/main/src/content-handlers/iiif/modules/uv-pdfcenterpanel-module/PDFCenterPanel.ts#L282

This link no longer works and has broken the loading of all PDFs on our site and other users of the UV

https://www.universalviewer.dev/#?xywh=-448%2C-197%2C3463%2C3936&iiifManifestId=https%3A%2F%2Fdigital.library.villanova.edu%2FItem%2Fvudl%3A294631%2FManifest

In all examples the browser is failing to load https://mozilla.github.io/pdf.js/build/pdf.js as this link has been deleted.

**Comment by demiankatz** [comment]
Thanks for reporting this, @404mike. I see from a comment in the code ("use pdfjs cdn, it just isn't working with webpack") that this problem was introduced as part of the migration to WebPack. Looks like this needs to be addressed (and we should check for and keep track of any other hard-coded CDN links), since not only does this make us vulnerable to the problem reported today, but it is also an unversioned link that might introduce weird incompatibilities.

I'm not sure what would be involved in fixing it, but @edsilv might want to consider making this part of the current sprint as it's obviously a high-priority issue.

In the meantime, as a workaround, you can set the `usePdfJs` option to `false` in the `options` section of your viewer configuration to use PDFObject instead. At Villanova, we've always had trouble with pdf.js, so we never use it. See our example configuration here:

https://digital.library.villanova.edu/themes/vudiglib/assets/viewer-config.json

**Comment by demiankatz** [comment]
Also, while I think the _correct_ solution here would be to fix whatever issues we're having with bundling PDF.js in WebPack, if we don't have time for that right now, there appear to be a variety of better CDN links available -- see:

https://mozilla.github.io/pdf.js/getting_started/#download

Maybe the PDF.js URL should be set up as a new config setting... but even a quick PR to replace the broken link with a non-broken link would be a start. @404mike, might you have time to try one of these alternate URLs and see if you can get a working build together as a PR?

**Comment by 404mike** [comment]
Hi @demiankatz thank you for the comments. I've made a hotfix to our dist code replace the mozilla links with https://cdnjs.com/libraries/pdf.js specifically: https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js & https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js

The pdfs are now loading on our site.

I haven't attempted to change the TS code as https://github.com/UniversalViewer/universalviewer/issues/913 is a blocker for us building any new version of the UV.

I will however make a PR today to replace the broken CDN as a stopgap until a better solution is found.

**Comment by 404mike** [comment]
Vercel build - https://universalviewer-kxq05q09m-mnemoscene.vercel.app/#?xywh=-1164%2C-197%2C4895%2C3936&iiifManifestId=https%3A%2F%2Fbiiif-template-example-3kntb3jpl-mnemoscene.vercel.app%2Fpdf%2Findex.json
