### ISSUE TITLE
Unable to open PDF manifest

### ISSUE THREAD

**Issue by akrizana** [UniversalViewer/universalviewer#963]
**UV version: 4.0.10**

```
 universalviewer@<4.0.10>
```

**I'm submitting a:**

- [x] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

PDF files cannot be displayed on the new version (even your test exaples), while the older version is displaying PDF files normally.
[Universal Viewer Examples (uv-v4.netlify.app)](https://uv-v4.netlify.app/#?manifest=%20https://ekultura-test.cdu.gov.hr/purl/url/VITOJ2AORUIGX4LUE2NYBGRSWXHKQ5F3&c=&m=&cv=&iiifManifestId=https%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb17502792%2Fmanifest&xywh=-2830%2C-275%2C9054%2C5493) - new version v4
[Universal Viewer Examples](https://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb17502792%2Fmanifest) - older version v3

**Expected behavior:**

Be able to see PDFs like in v3

**Steps to reproduce:**

You can open the links I have pasted in this ticket, or visit website https://universalviewer.io/ --> View manifest --> https://uv-v4.netlify.app/#?manifest=&c=&m=&cv=&xywh=-2441%2C-197%2C7449%2C3936 --> Select one of the default PDF manifests.

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by demiankatz** [comment]
@akrizana, it sounds like you may be describing the problem that was fixed by #940 (and discussed in #939). This fix was released in UV 4.0.23. I suspect that you need to upgrade to a newer UV release, or else backport the fix to your version and rebuild. Please let me know if you need additional help!

**Comment by demiankatz** [comment]
Hmm, that is strange; what method are you using to load the UV? Are you getting any errors in your console? I know that some others are successfully running newer releases...

**Comment by demiankatz** [comment]
I wonder if this might be related to the issue fixed by #959 (which was merged recently and hasn't been released yet). Can you try this with a dev build?

**Comment by akrizana** [comment]
Works like a charm. Thank you. Could you tell me can I use this version until the release or I should wait for the official release?

**Comment by demiankatz** [comment]
@akrizana, if it's working for your purposes, it's probably okay to use it. Official releases are helpful for support purposes since they're easy to talk about, but it may be a little while before the next official release as the community is trying to formalize some of our procedures, and that may take time. I wouldn't want you to be stuck with a broken viewer in the meantime!

I think this issue is now resolved, so I'm going to close it... but please feel free to open a new one if you run into further trouble.
